on:
  [push, pull_request]

name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1.0.0
    - name: Build container
      run: |
        docker build -t blog .
    # - name: Setup AWS and grab ECR creds
    # - name: Build, tag, push container to ECR
    # - name: Build, deploy task definition
    # - name: Report cluster status
